/* Generated By:JavaCC: Do not edit this line. ValidateFileConstants.java */
package logic.Parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ValidateFileConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGRAPH = 4;
  /** RegularExpression Id. */
  int LABEL = 5;
  /** RegularExpression Id. */
  int PERIPHE = 6;
  /** RegularExpression Id. */
  int FINAL_STATE = 7;
  /** RegularExpression Id. */
  int NAME = 8;
  /** RegularExpression Id. */
  int OPENFIELD = 9;
  /** RegularExpression Id. */
  int CLOSEFIELD = 10;
  /** RegularExpression Id. */
  int OPEN = 11;
  /** RegularExpression Id. */
  int CLOSE = 12;
  /** RegularExpression Id. */
  int EQUALS = 13;
  /** RegularExpression Id. */
  int ARROW = 14;
  /** RegularExpression Id. */
  int SEMICOLON = 15;
  /** RegularExpression Id. */
  int QUOTE = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"digraph\"",
    "\"label\"",
    "\"peripheries\"",
    "\"2\"",
    "<NAME>",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"->\"",
    "\";\"",
    "\"\\\'\"",
  };

}
