/* Generated By:JavaCC: Do not edit this line. ValidateFileConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ValidateFileConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGRAPH = 4;
  /** RegularExpression Id. */
  int LABEL = 5;
  /** RegularExpression Id. */
  int PERIPHE = 6;
  /** RegularExpression Id. */
  int NAME = 7;
  /** RegularExpression Id. */
  int FINAL_STATE = 8;
  /** RegularExpression Id. */
  int INTEGER = 9;
  /** RegularExpression Id. */
  int OPENFIELD = 10;
  /** RegularExpression Id. */
  int CLOSEFIELD = 11;
  /** RegularExpression Id. */
  int OPEN = 12;
  /** RegularExpression Id. */
  int CLOSE = 13;
  /** RegularExpression Id. */
  int EQUALS = 14;
  /** RegularExpression Id. */
  int ARROW = 15;
  /** RegularExpression Id. */
  int SEMICOLON = 16;
  /** RegularExpression Id. */
  int LF = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"digraph\"",
    "\"label\"",
    "\"peripheries\"",
    "<NAME>",
    "\"2\"",
    "<INTEGER>",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"->\"",
    "\";\"",
    "\"\\n\"",
  };

}
